---

- name: Install and configure snmpd
  hosts: all
  become: true
  become_user: root
  vars:
    user:
      login: deploy
      password_hash:
        "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3F\
        BTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      authorized_key:
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr\
        +kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6I\
        edplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2\
        hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZE\
        nDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHln\
        VYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
  tasks:
    - name: Create admin account
      user:
        name: "{{ user.login }}"
        shell: /bin/bash
        update_password: always
        password: "{{ user.password_hash }}"
    - name: Add admin to sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ user.login }} ALL=(ALL:ALL) NOPASSWD:ALL"
    - name: Create authorized key for admin
      authorized_key:
        user: "{{ user.login }}"
        state: present
        key: "{{ user.authorized_key }}"
    - name: Enable EPEL Repository
      yum:
        name: epel-release
        state: present
    - name: Install software
      package:
        name:
          - iptables-services
          - net-snmp
          - net-snmp-utils
        state: present
    - name: Configure snmpd
      copy:
        src: ./snmpd.conf
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: root
        mode: 644
    - name: Allow access via SNMP
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: 161
        ctstate: NEW
        jump: ACCEPT
    - name: Start snmpd
      systemd:
        name: snmpd
        enabled: true
        state: started
